version: "3.1"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    ## TODO: mount local code path so as to stop rebuilds of docker compose
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
